SELECT name FROM MEMBER WHERE join_date> '2000-09-01';
SELECT * FROM MEMBER WHERE join_date BETWEEN '1995-10-01' AND '2019-10-01';
SELECT * FROM BOOK WHERE (price BETWEEN 15 AND 20) OR (pub_id = (SELECT pub_id FROM PUBLISHER WHERE name='Oxford'));
SELECT title FROM book INNER JOIN BORROWING_BOOK ON BORROWING_BOOK.book_id=BOOK.book_id INNER JOIN MEMBER ON BORROWING_BOOK.member_id=MEMBER.member_id WHERE MEMBER.name='Scot Reinger';
SELECT name FROM MEMBER INNER JOIN BORROWING_BOOK ON MEMBER.member_id=BORROWING_BOOK.member_id WHERE BORROWING_BOOK.borrow_date BETWEEN '2019-01-01' AND '2019-12-31';